# Setup
title:               NHL Unofficial Analysts
tagline:             'We do not play hockey'
description:         'No really, we prefer soccer'
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Pascal Archambault, Jeremy Parent, Marcos Souto, Charles Collela

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
